Repository microsoft/fluentui-system-icons, pull requests merged in 2020-06, with the labels that each got.

#14 Updating Thumb Like and Dislike
  assets/Thumb Dislike/PDF/ic_fluent_thumb_dislike_20_filled.pdf
  assets/Thumb Dislike/PDF/ic_fluent_thumb_dislike_20_regular.pdf
  assets/Thumb Dislike/PDF/ic_fluent_thumb_dislike_24_filled.pdf
  assets/Thumb Dislike/PDF/ic_fluent_thumb_dislike_24_regular.pdf
  assets/Thumb Dislike/SVG/ic_fluent_thumb_dislike_20_filled.svg
  assets/Thumb Dislike/SVG/ic_fluent_thumb_dislike_20_regular.svg
  assets/Thumb Dislike/SVG/ic_fluent_thumb_dislike_24_filled.svg
  assets/Thumb Dislike/SVG/ic_fluent_thumb_dislike_24_regular.svg
  assets/Thumb Like/PDF/ic_fluent_thumb_like_20_filled.pdf
  assets/Thumb Like/PDF/ic_fluent_thumb_like_20_regular.pdf
  assets/Thumb Like/PDF/ic_fluent_thumb_like_24_filled.pdf
  assets/Thumb Like/PDF/ic_fluent_thumb_like_24_regular.pdf
  assets/Thumb Like/SVG/ic_fluent_thumb_like_20_filled.svg
  assets/Thumb Like/SVG/ic_fluent_thumb_like_20_regular.svg
  assets/Thumb Like/SVG/ic_fluent_thumb_like_24_filled.svg
  assets/Thumb Like/SVG/ic_fluent_thumb_like_24_regular.svg
Labels: enhancement

#16 Add subspecs so consumers can just pull in the parts they need
  ios/FluentIcons.podspec
Labels: CI/publish

#25 Fix CI status badge
  README.md
Labels: bug

#28 Update old repo reference in CI script
  .github/workflows/publish.yml
Labels: bug

#29 Update carthage references to new repo
  README.md
  ios/README.md
Labels: CI/publish
